/**
 * @file item.entity.ts
 * @brief TypeORM entity definition for the Item resource.
 * @details Maps the Item model to a PostgreSQL table 'items' with columns id, name,
 *          description, dateOfBirth, sex, phoneNumber, address, createdAt, and updatedAt.
 * @author Victor Yeh
 * @date 2026-02-20
 * @copyright MIT License
 */

import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';

/**
 * @class Item
 * @brief Entity representing a single item (record) stored in the database.
 * @type class
 * @details Persisted in table 'items'. id is UUID primary key; name is required;
 *          description, dateOfBirth, sex, phoneNumber, address are optional;
 *          createdAt and updatedAt are set automatically by TypeORM.
 */
@Entity('items')
export class Item {
  /**
   * @var id
   * @brief Unique identifier for the item.
   * @type string
   * @details UUID v4, auto-generated by the database on insert. Read-only after creation.
   */
  @PrimaryGeneratedColumn('uuid')
  readonly id!: string;

  /**
   * @var name
   * @brief Display name of the item.
   * @type string
   * @details Required, max length 255 characters.
   */
  @Column({ type: 'varchar', length: 255 })
  name!: string;

  /**
   * @var description
   * @brief Optional longer description of the item.
   * @type string
   * @details Stored as text; may be empty string.
   */
  @Column({ type: 'text', default: '' })
  description!: string;

  /**
   * @var dateOfBirth
   * @brief Date of birth; optional.
   * @type Date | null
   * @details Stored as date in PostgreSQL; null if not provided.
   */
  @Column({ type: 'date', nullable: true })
  dateOfBirth!: Date | null;

  /**
   * @var sex
   * @brief Sex (e.g. male, female, other); optional, defaults to empty string.
   * @type string
   * @details Max length 50.
   */
  @Column({ type: 'varchar', length: 50, default: '' })
  sex!: string;

  /**
   * @var phoneNumber
   * @brief Phone number; optional, defaults to empty string.
   * @type string
   * @details Max length 50.
   */
  @Column({ type: 'varchar', length: 50, default: '' })
  phoneNumber!: string;

  /**
   * @var address
   * @brief Address; optional, defaults to empty string.
   * @type string
   * @details Stored as text.
   */
  @Column({ type: 'text', default: '' })
  address!: string;

  /**
   * @var createdAt
   * @brief Timestamp when the record was created.
   * @type Date
   * @details Set automatically by TypeORM on insert. Read-only after creation.
   */
  @CreateDateColumn({ name: 'created_at' })
  readonly createdAt!: Date;

  /**
   * @var updatedAt
   * @brief Timestamp when the record was last updated.
   * @type Date
   * @details Set automatically by TypeORM on insert and on every update.
   */
  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt!: Date;
}
